### ISSUE TITLE
Make Question Display cleaner

### ISSUE THREAD

**Issue by johnhbenetech** [CodeAllianceOrg/odk2#11]
Any questions in a section should be displayed as followed:

- left aligned instead of center aligned
- remove bullet points in front of question
- the text that shows should be the base display text, instead of the name

![image](https://user-images.githubusercontent.com/12927553/31689606-cc93d23c-b344-11e7-85f3-689bec172ee2.png)

**Comment by russon77** [comment]
- better selection icons (unselected vs selected state)
- selected button moved, maybe rearrange to select, spacing, shift up/down, spacing, delete.
