### ISSUE TITLE
data types

### ISSUE THREAD

**Issue by russon77** [CodeAllianceOrg/odk2#2]
let's enumerate the possible data types / questions and their properties.

**Comment by bripc** [comment]
I started a document [here](https://docs.google.com/spreadsheets/d/1tQXUXfEjm9oyuFyc3fdKeUPpxFeFsBOq0G0E7mns3-I/edit?usp=sharing) with the data types we could include. It is based off of [this documentation](https://opendatakit.org/use/2_0_tools/older-versions/xlsxconverter-beta-2-0-v2/) for the ODK XLSXConverter beta.

**Comment by johnhbenetech** [comment]
I've requested write access to this docs so I can add relative priority column. 

As a first pass, these would be the minimum viable fields for the first release:
* group
* date
* decimal
* geopoint
* image
* integer
* note
* select_one_dropdown
--properties include set of choices
* string
* text
* video

+ PovertyStoplight Question (select_one_slider)
^ This is a custom Benetech questiontype that is similar to select_one_grid. It has included text question followed by exactly 3 options each with a photo and text description. One option represents a 'green' or satisfactory option, followed by a yellow and a red option. I've attached an xlsx with example stoplight and choices sheet.


Properties that would be needed for each question:
- Required (true/false)
- Name (system readable representation)
- display.text (default text displayed to the end user)
- display.text.spanish (other language display text)
- values_list (for multiple choice questions)

Choice List properties:
- choice_list_name
- data_value
- display.text
- display.text.spanish
- display.image

**Comment by russon77** [comment]
i believe that @bripc used an older version of the documentation. https://opendatakit.org/use/2_0_tools/active-distribution/application-designer-rev-208/xlsx-converter-rev-208/ seems to be the most recently updated documentation regarding 2.0 data types.

**Comment by bripc** [comment]
I compared our current document with that updated link that @russon77 sent and everything should be up to date now. The data types are the same in both it seems, but I included that link ^ in the document instead.

**Comment by russon77** [comment]
@johnhbenetech are the `groups` in this project equivalent to `begin screen`/`end screen` or `do section`/section labels?

**Comment by johnhbenetech** [comment]
@russon77 Sections. Then each section will just be one screen to start. In the futrue we can add ability to do pages within a group.
