### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by russon77** [CodeAllianceOrg/odk2#3]
translations of the app itself.

**Comment by russon77** [comment]
@rwiepking any updates?

**Comment by rwiepking** [comment]
Hi, not sure I should have been assigned anything, Im a sysadmin at Benetech and I only manage our orgs on git. 

Cheers,
Rick

**Comment by russon77** [comment]
my apologies @rwiepking !

**Comment by rwiepking** [comment]
no worries!

**Comment by russon77** [comment]
## application translation support todo

- [ ] https://github.com/ngx-translate/core
- [ ] translation support for _most_ existing strings 

### blocked by

PR https://github.com/CodeAllianceOrg/odk2/pull/16 includes a lot of text updates, so to avoid the inevitable conflicts we'll put off translation support until the PR is merged!

**Comment by russon77** [comment]
translation support has been implemented! i suggest holding off on actual translation until we reach a release, at which point we translate the release. otherwise it gets very messy very fast with trying to keep pace with translations and changing strings!
