### ISSUE TITLE
how do we know we're doing it right?

### ISSUE THREAD

**Issue by russon77** [CodeAllianceOrg/odk2#5]
given the complexity of the application, we need to be able to identify errors sooner rather than later.

while we can end to end test the website for site specific errors, i suggest we start integrating the json <-> odk2.0 library asap in order to provide a "start to finish" testing environment for the product owners.

at the same time, i propose that we integrate CI so that deployments to a dev site are always up to date and the product owner can check in on the progress of the site itself at any time.

**Comment by johnhbenetech** [comment]
For CI/testing purposes this is probably a good jumping off point:
https://github.com/opendatakit/app-designer/tree/master/xlsxconverter

it contains the javascript that flips XLSX->ODK 2 readable directory. 

The benetech fork:
https://github.com/benetech/app-designer/tree/master/xlsxconverter

May be more relevant as in include some customization from our side to work with our 'stoplight' question type.

**Comment by russon77** [comment]
@johnhbenetech do you know of any documentation for the xlsx converter? for starters, is it compatible with ODK 2.0?

**Comment by johnhbenetech** [comment]
@russon77 Yeah all xlsx related stuff is exclusively ODK 2.0. ODK 1.0 is all XML/XForms.

This is the only docs I know about: https://opendatakit.org/use/2_0_tools/older-versions/xlsxconverter-beta-2-0-v2/

It's more about the formatting of the xlsx than the converter code. 

In case its helpful we have a java port of the js xlsx->json:
https://github.com/benetech/xlsx-to-json-hamster

And then also the xlsx-> ODK converter (which calls the previous script):
https://github.com/benetech/xlsx-to-odk-hamster


And then just a reminder that the ODK source is here:
https://github.com/opendatakit/app-designer/tree/master/xlsxconverter

**Comment by johnhbenetech** [comment]
Also some nuggets here:
https://github.com/opendatakit/opendatakit/wiki/Tool-Suite-Javascript-framework-and-formDef.json-(Survey)-format

**Comment by russon77** [comment]
@johnhbenetech thanks! i setup a basic library today that tests against https://github.com/benetech/app-designer/tree/master/xlsxconverter catching errors.

it was very hard to keep my head straight with the different converters and this specific project's requirements - the focus here being input/output of an ODK2.0 XLSX document.
